export default {
  airplane: () => import('@/components/IconAirplane.vue'),
  'alarm clock': () => import('@/components/IconAlarmClock.vue'),
  anchor: () => import('@/components/IconAnchor.vue'),
  bug: () => import('@/components/IconBug.vue'),
  car: () => import('@/components/IconCar.vue'),
  eye: () => import('@/components/IconEye.vue'),
  flask: () => import('@/components/IconFlask.vue'),
  ghost: () => import('@/components/IconGhost.vue'),
  heart: () => import('@/components/IconHeart.vue'),
  hippo: () => import('@/components/IconHippo.vue'),
  lira: () => import('@/components/IconLira.vue'),
  magnet: () => import('@/components/IconMagnet.vue'),
  moon: () => import('@/components/IconMoon.vue'),
  snowflake: () => import('@/components/IconSnowflake.vue'),
  'spock hand': () => import('@/components/IconSpockHand.vue'),
  sun: () => import('@/components/IconSun.vue'),
  trophy: () => import('@/components/IconTrophy.vue'),
  umbrella: () => import('@/components/IconUmbrella.vue'),
}
